/********************************************************************/
/* errno.h  v6.10                                                   */
/* Copyright (c) 1991 Texas Instruments Incorporated                */
/********************************************************************/
#ifndef _ERRNO
#define _ERRNO
extern int errno;
#endif

#ifndef EDOM
#define EDOM   1
#endif

#ifndef ERANGE
#define ERANGE 2
#endif

#ifndef ENOENT
#define ENOENT 3
#endif
